# Generated by Django 2.0 on 2018-01-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('lname', models.CharField(max_length=100)),
                ('permissions', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('item_ids', models.CharField(max_length=5000)),
                ('address', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=30)),
            ],
        ),
    ]
