# Generated by Django 2.0 on 2018-01-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbadmin', '0002_level_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('cprice', models.FloatField()),
                ('item_ids', models.CharField(max_length=100)),
                ('picture', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('isvip', models.BooleanField(default=False)),
                ('weichar', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('iid', models.IntegerField(primary_key=True, serialize=False)),
                ('iname', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('category_id', models.IntegerField()),
                ('picture', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('slid', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField()),
                ('shop_id', models.IntegerField()),
                ('combo_ids', models.CharField(max_length=300)),
                ('item_ids', models.CharField(max_length=300)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='levelid',
            new_name='level_id',
        ),
    ]
