# Generated by Django 2.0 on 2018-01-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jbadmin', '0003_auto_20180101_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
