# Generated by Django 2.0 on 2018-01-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbadmin', '0005_auto_20180103_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.FileField(upload_to='./upload'),
        ),
    ]
