# Generated by Django 2.0 on 2018-01-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbadmin', '0006_auto_20180104_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.FileField(upload_to='./upload/itempic/'),
        ),
    ]
