# Generated by Django 2.0 on 2018-01-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbadmin', '0007_auto_20180104_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(upload_to='./upload/itempic/'),
        ),
    ]
