# Generated by Django 2.0 on 2018-01-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbadmin', '0010_auto_20180104_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cdepend_id',
            field=models.IntegerField(default=0),
        ),
    ]
