# Generated by Django 2.0 on 2018-01-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbadmin', '0011_category_cdepend_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
