# Generated by Django 2.0 on 2018-01-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbadmin', '0012_auto_20180107_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
